---
title: "Table and Graph for 10k Rate"
author: "Michael Quinn Maguire, MS"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(tidyverse)
library(tidylog)
```

- Read in the file with the `RatePer100k` variable.

```{r}
base_rate_file <- read_csv(file = './data/clean/20220218_fl-moud-aggregate.csv') |>
  mutate(yearQuarter = zoo::as.yearqtr(yearQuarter),
         ratePer10k = round(ratePer100k / 10, digits = 2))

base_seq_file <- base_rate_file |>
  distinct(yearQuarter) |>
  mutate(seq = row_number())

xMinimum <- base_seq_file$seq[base_seq_file$yearQuarter == "2020 Q1"]
xMaximum <- base_seq_file$seq[base_seq_file$yearQuarter == "2020 Q2"]

read_csv(file = './data/clean/20220218_fl-quarterly-enrollment-denominator.csv')

base_rate_file_buprenorphine <- base_rate_file |>
  group_by(yearQuarter) |>
  summarize(totalPrescriptions = sum(totalRX))

base_rate_denom <- base_rate_file |> 
  distinct(yearQuarter, total)

base_rate_final <- base_rate_file_buprenorphine |>
  left_join(base_rate_denom, by = 'yearQuarter') |>
  mutate(prescriptionsByQuarter = round(((totalPrescriptions / total) * 10000), digits = 2)) |>
  rename(`Year Quarter` = yearQuarter, `Prescriptions per 10,000 Medicaid Enrollees` = prescriptionsByQuarter) |>
  select(`Year Quarter`, `Prescriptions per 10,000 Medicaid Enrollees`)

base_rate_drugs_final <- base_rate_file |>
  select(yearQuarter, allDrugs, ratePer10k) |>
  rename(`Year Quarter` = yearQuarter, Medication = allDrugs, `Prescriptions per 10,000 Medicaid Enrollees` = ratePer10k)

write_csv(base_rate_drugs_final, file = paste0('./data/clean/', format(Sys.Date(), '%Y%m%d'), '_individual-drugs-per-10k-enrollees-by-year-and-quarter.csv'))

write_csv(base_rate_final, file = paste0('./data/clean/', format(Sys.Date(), '%Y%m%d'), '_prescriptions-per-10k-enrollees-by-year-and-quarter.csv'))
```

```{r,, fig.width = 20, height = 12}
base_rate_plot_by_drug <- base_rate_file |>
  ggplot() +
  geom_point(aes(x = as.factor(yearQuarter), y = ratePer10k, group = allDrugs, color = allDrugs), size = 2) +
  geom_line(aes(x = as.factor(yearQuarter), y = ratePer10k, group = allDrugs, color = allDrugs), size = 1) +
  annotate('rect', xmin = xMinimum, xmax = xMaximum, ymin = -Inf, ymax = Inf, fill = 'red', alpha = 0.1) +
  scale_color_manual(values = c("Bunavail" = "grey", "Buprenorphine" = "#FA841A", "Suboxone" = "#004DA9", "Zubsolv" = "chartreuse4")) +
  xlab('Year - Quarter') +
  ylab('Prescription Rate per 10,000 Adult Medicaid Enrollees') +
  ggtitle("Normalized MOUD Prescription Rate by Medication - Florida") +
  hrbrthemes::theme_ipsum_rc() +
  theme(
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size = 16, hjust = 0.5, vjust = -1),
    axis.title.y = element_text(size = 16, hjust = 0.5),
    legend.position = 'bottom',
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.key.size = unit(3, 'line')
  ) +
  labs(color = 'Medication Name')

base_rate_plot_by_drug
```

```{r, fig.width = 20, height = 12}
base_rate_plot <- base_rate_final |>
  ggplot(aes(x = as.factor(`Year Quarter`), y = `Prescriptions per 10,000 Medicaid Enrollees`)) +
  geom_point() +
  geom_line(aes(group = 1)) +
  annotate('rect', xmin = xMinimum, xmax = xMaximum, ymin = -Inf, ymax = Inf, fill = 'red', alpha = 0.1) +
  xlab('Year - Quarter') +
  ylab('Prescription Rate per 10,000 Adult Medicaid Enrollees') +
  ggtitle("Normalized MOUD Prescription Rate Overall - Florida") +
  hrbrthemes::theme_ipsum_rc() +
  theme(
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14),
    axis.title.x = element_text(size = 16, hjust = 0.5, vjust = -1),
    axis.title.y = element_text(size = 16, hjust = 0.5),
    legend.position = 'bottom',
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.key.size = unit(3, 'line')
  ) +
  labs(color = 'Medication') +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 80))

base_rate_plot
```

```{r}
Cairo::CairoPDF(file = paste0('./plots/', format(Sys.Date(), '%Y%m%d'), '_plots-for-grant-updates.pdf'), onefile = TRUE, width = 18, height = 9)
base_rate_plot
base_rate_plot_by_drug
dev.off()
```